In [1]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.5.1
CUDA available: False


In [5]:
# Creates a tensor [Tensor is for serialization/deserialization] - human --> tensor --> model --> tensor --> human output
scalar = torch.tensor(7)
scalar # no dimensions/single number

#get tensor back
scalar.item()

7

In [14]:
vector = torch.tensor([1,2,3])
# dimensions is basically - just the number of the square brackets
print(vector.ndim)
print(vector.shape)

print("-----------------")

matrix = torch.tensor([[1,2],[3,4]])
print(matrix.ndim)
print(matrix.shape)

print("-----------------")

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor.ndim)
print(tensor.shape)

print("-----------------")

tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor.ndim)
print(tensor.shape) 


1
torch.Size([3])
-----------------
2
torch.Size([2, 2])
-----------------
3
torch.Size([1, 3, 3])
-----------------
3
torch.Size([2, 2, 3])


In [20]:
random_tensor = torch.rand(4,3,2)
print(random_tensor)

tensor([[[0.5975, 0.0902],
         [0.5519, 0.5971],
         [0.4623, 0.6878]],

        [[0.5721, 0.6929],
         [0.6573, 0.1327],
         [0.8041, 0.4232]],

        [[0.0735, 0.5664],
         [0.4889, 0.1427],
         [0.4119, 0.4340]],

        [[0.9998, 0.9831],
         [0.0720, 0.6673],
         [0.9493, 0.1465]]])


In [7]:
image = torch.rand(size=(224, 224, 3))  # height, width, color_channels [R, G , B]
# It is the same as torch.rand(224, 224, 3)
print(image)

tensor([[[0.2756, 0.8736, 0.8287],
         [0.8422, 0.8185, 0.4799],
         [0.9102, 0.5261, 0.8229],
         ...,
         [0.2638, 0.6988, 0.9368],
         [0.3347, 0.1590, 0.2872],
         [0.2473, 0.5816, 0.1971]],

        [[0.9184, 0.9367, 0.1332],
         [0.3639, 0.2123, 0.0535],
         [0.6338, 0.4432, 0.5805],
         ...,
         [0.9741, 0.0602, 0.6299],
         [0.1327, 0.2192, 0.9668],
         [0.2781, 0.2530, 0.1315]],

        [[0.6415, 0.7631, 0.1628],
         [0.6155, 0.1745, 0.3673],
         [0.9439, 0.6087, 0.9162],
         ...,
         [0.1668, 0.9064, 0.7746],
         [0.1628, 0.2767, 0.9714],
         [0.9476, 0.3132, 0.4228]],

        ...,

        [[0.8822, 0.2150, 0.2794],
         [0.0552, 0.1489, 0.2230],
         [0.8434, 0.1056, 0.1495],
         ...,
         [0.9053, 0.7623, 0.3824],
         [0.8893, 0.8821, 0.9954],
         [0.6757, 0.1857, 0.0201]],

        [[0.4108, 0.8148, 0.3008],
         [0.4622, 0.0105, 0.0198],
         [0.

In [8]:
range_tensor = torch.arange(1, 100, 5) # start, end, step
print(range_tensor)

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])


In [10]:
print(image.shape)
print(image.dtype)
print(image.device)

torch.Size([224, 224, 3])
torch.float32
cpu


In [15]:
# Matrix Multiplcation
one = torch.rand(2,5)
two = torch.rand(5,3)
#result1 = one * two #this is element multiplication - wont work here bcs the dimensions are not same
result2 = torch.matmul(one, two)
print(result2)

tensor([[1.0253, 1.1457, 0.7577],
        [1.3628, 1.5013, 1.4170]])


In [17]:
tens = torch.rand(size=(2,3), dtype=torch.float32)
print(tens)
trans = tens.T #Transpose
print(trans)

tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])
tensor([[0.1088, 0.6790],
        [0.1637, 0.9155],
        [0.7025, 0.2418]])


In [21]:
r = torch.arange(0,100,10)
r.type(torch.float32).mean() #mean can only worj on float and complex dtype
# This ^ is how you change the type

tensor(45.)

In [24]:
reverse = torch.arange(100, 0, -10)
print(reverse.argmin())
print(reverse.argmax())

tensor(9)
tensor(0)


## reshaping, stacking, squeezing, unsqueezing

In [31]:
x = torch.rand(size=(1,3,1))
print(x)
x.shape

tensor([[[0.1115],
         [0.2477],
         [0.6524]]])


torch.Size([1, 3, 1])

In [32]:
print(x.squeeze())
x.squeeze().shape

tensor([0.1115, 0.2477, 0.6524])


torch.Size([3])

In [34]:
x = torch.arange(1, 10, 1)
y = x.reshape(1,3,3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [40]:
y[0][2][2]

tensor(9)

In [44]:
y[:, :, 2]

tensor([[3, 6, 9]])

In [3]:
#Linear Regression
import torch
from torch import nn

weights = 0.7
bias = 0.3

X = torch.arange(0, 1, 0.02).unsqueeze(dim=1)
# Unsqeeze is used to add a dimension to the tensor, adding another bracket to the tensor
y = weights*X + bias

print(X[:10])
y[:10]

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800]])


tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260]])

In [4]:
#Splitting data into training and test steps
train_split = int(0.8*len(X)) #Can also use scikit learn's train_test_split
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

In [17]:
#nn.Module - Base class for all neural network modules [IMPORTANT]

from torch import nn

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))
        self.bias = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))
        #requires_grad - For Gradient Descent
    
    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return self.weights*X + self.bias


In [19]:
torch.manual_seed(42)
model = LinearRegressionModel()
list(model.parameters())

[Parameter containing:
 tensor([0.8823], requires_grad=True),
 Parameter containing:
 tensor([0.9150], requires_grad=True)]

In [20]:

model.state_dict()

OrderedDict([('weights', tensor([0.8823])), ('bias', tensor([0.9150]))])

In [21]:
# Loss Function
loss_fn = nn.L1Loss()

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) #lr = learning rate

In [35]:
# Training Loop + testing loop
epochs = 100

for epoch in range(epochs):
    model.train() # training mode - sets all parameters that require gradients to require gradients

    #1. Forward Pass
    y_pred = model(X_train)

    #2. Calculate Loss
    loss = loss_fn(y_pred, y_train) #difference between predicted and actual values

    #3. optimizer.zero_grad() - clears the gradients of all optimized tensors
    optimizer.zero_grad()  #just init to zero in each iteration

    #4. backward pass - backpropagation
    loss.backward()

    #5. step the optimizer - perfor GD
    optimizer.step()

print(loss)


tensor(0.0071, grad_fn=<MeanBackward0>)


In [36]:
model.state_dict() #note that the weights and bias has changed from the initial random values - look above

OrderedDict([('weights', tensor([0.6938])), ('bias', tensor([0.2980]))])